/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage
 * @generated
 */
public interface MyDslFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MyDslFactory eINSTANCE = org.xtext.example.mydsl.myDsl.impl.MyDslFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Model</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Model</em>'.
   * @generated
   */
  Model createModel();

  /**
   * Returns a new object of class '<em>Top Level Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Top Level Operation</em>'.
   * @generated
   */
  TopLevelOperation createTopLevelOperation();

  /**
   * Returns a new object of class '<em>Load Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load Operation</em>'.
   * @generated
   */
  LoadOperation createLoadOperation();

  /**
   * Returns a new object of class '<em>Load JSON</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load JSON</em>'.
   * @generated
   */
  LoadJSON createLoadJSON();

  /**
   * Returns a new object of class '<em>Load XML</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load XML</em>'.
   * @generated
   */
  LoadXML createLoadXML();

  /**
   * Returns a new object of class '<em>Load YAML</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Load YAML</em>'.
   * @generated
   */
  LoadYAML createLoadYAML();

  /**
   * Returns a new object of class '<em>Concat Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Concat Operation</em>'.
   * @generated
   */
  ConcatOperation createConcatOperation();

  /**
   * Returns a new object of class '<em>Filter Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Filter Operation</em>'.
   * @generated
   */
  FilterOperation createFilterOperation();

  /**
   * Returns a new object of class '<em>Save Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Save Operation</em>'.
   * @generated
   */
  SaveOperation createSaveOperation();

  /**
   * Returns a new object of class '<em>Print Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Operation</em>'.
   * @generated
   */
  PrintOperation createPrintOperation();

  /**
   * Returns a new object of class '<em>Print Table</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Print Table</em>'.
   * @generated
   */
  PrintTable createPrintTable();

  /**
   * Returns a new object of class '<em>Rename Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Rename Operation</em>'.
   * @generated
   */
  RenameOperation createRenameOperation();

  /**
   * Returns a new object of class '<em>Limit Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Limit Operation</em>'.
   * @generated
   */
  LimitOperation createLimitOperation();

  /**
   * Returns a new object of class '<em>Arg Max Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arg Max Operation</em>'.
   * @generated
   */
  ArgMaxOperation createArgMaxOperation();

  /**
   * Returns a new object of class '<em>Arg Min Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Arg Min Operation</em>'.
   * @generated
   */
  ArgMinOperation createArgMinOperation();

  /**
   * Returns a new object of class '<em>Select Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Select Operation</em>'.
   * @generated
   */
  SelectOperation createSelectOperation();

  /**
   * Returns a new object of class '<em>Drop Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Drop Operation</em>'.
   * @generated
   */
  DropOperation createDropOperation();

  /**
   * Returns a new object of class '<em>Process Folders Operation</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Process Folders Operation</em>'.
   * @generated
   */
  ProcessFoldersOperation createProcessFoldersOperation();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MyDslPackage getMyDslPackage();

} //MyDslFactory
