/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Folders Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ProcessFoldersOperation#getFolders <em>Folders</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.ProcessFoldersOperation#getFolderOperations <em>Folder Operations</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProcessFoldersOperation()
 * @model
 * @generated
 */
public interface ProcessFoldersOperation extends TopLevelOperation
{
  /**
   * Returns the value of the '<em><b>Folders</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folders</em>' attribute list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProcessFoldersOperation_Folders()
   * @model unique="false"
   * @generated
   */
  EList<String> getFolders();

  /**
   * Returns the value of the '<em><b>Folder Operations</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.example.mydsl.myDsl.TopLevelOperation}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Folder Operations</em>' containment reference list.
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getProcessFoldersOperation_FolderOperations()
   * @model containment="true"
   * @generated
   */
  EList<TopLevelOperation> getFolderOperations();

} // ProcessFoldersOperation
