/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.RenameOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Rename Operation</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RenameOperationImpl#getOriginal <em>Original</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RenameOperationImpl#getRenamed <em>Renamed</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.impl.RenameOperationImpl#getTable <em>Table</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RenameOperationImpl extends TopLevelOperationImpl implements RenameOperation
{
  /**
   * The default value of the '{@link #getOriginal() <em>Original</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriginal()
   * @generated
   * @ordered
   */
  protected static final String ORIGINAL_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getOriginal() <em>Original</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOriginal()
   * @generated
   * @ordered
   */
  protected String original = ORIGINAL_EDEFAULT;

  /**
   * The default value of the '{@link #getRenamed() <em>Renamed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRenamed()
   * @generated
   * @ordered
   */
  protected static final String RENAMED_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getRenamed() <em>Renamed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getRenamed()
   * @generated
   * @ordered
   */
  protected String renamed = RENAMED_EDEFAULT;

  /**
   * The default value of the '{@link #getTable() <em>Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTable()
   * @generated
   * @ordered
   */
  protected static final String TABLE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getTable() <em>Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTable()
   * @generated
   * @ordered
   */
  protected String table = TABLE_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RenameOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.RENAME_OPERATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getOriginal()
  {
    return original;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOriginal(String newOriginal)
  {
    String oldOriginal = original;
    original = newOriginal;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RENAME_OPERATION__ORIGINAL, oldOriginal, original));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getRenamed()
  {
    return renamed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setRenamed(String newRenamed)
  {
    String oldRenamed = renamed;
    renamed = newRenamed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RENAME_OPERATION__RENAMED, oldRenamed, renamed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getTable()
  {
    return table;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTable(String newTable)
  {
    String oldTable = table;
    table = newTable;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MyDslPackage.RENAME_OPERATION__TABLE, oldTable, table));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MyDslPackage.RENAME_OPERATION__ORIGINAL:
        return getOriginal();
      case MyDslPackage.RENAME_OPERATION__RENAMED:
        return getRenamed();
      case MyDslPackage.RENAME_OPERATION__TABLE:
        return getTable();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MyDslPackage.RENAME_OPERATION__ORIGINAL:
        setOriginal((String)newValue);
        return;
      case MyDslPackage.RENAME_OPERATION__RENAMED:
        setRenamed((String)newValue);
        return;
      case MyDslPackage.RENAME_OPERATION__TABLE:
        setTable((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.RENAME_OPERATION__ORIGINAL:
        setOriginal(ORIGINAL_EDEFAULT);
        return;
      case MyDslPackage.RENAME_OPERATION__RENAMED:
        setRenamed(RENAMED_EDEFAULT);
        return;
      case MyDslPackage.RENAME_OPERATION__TABLE:
        setTable(TABLE_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MyDslPackage.RENAME_OPERATION__ORIGINAL:
        return ORIGINAL_EDEFAULT == null ? original != null : !ORIGINAL_EDEFAULT.equals(original);
      case MyDslPackage.RENAME_OPERATION__RENAMED:
        return RENAMED_EDEFAULT == null ? renamed != null : !RENAMED_EDEFAULT.equals(renamed);
      case MyDslPackage.RENAME_OPERATION__TABLE:
        return TABLE_EDEFAULT == null ? table != null : !TABLE_EDEFAULT.equals(table);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (original: ");
    result.append(original);
    result.append(", renamed: ");
    result.append(renamed);
    result.append(", table: ");
    result.append(table);
    result.append(')');
    return result.toString();
  }

} //RenameOperationImpl
