/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.TopLevelOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Top Level Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class TopLevelOperationImpl extends MinimalEObjectImpl.Container implements TopLevelOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected TopLevelOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.TOP_LEVEL_OPERATION;
  }

} //TopLevelOperationImpl
