/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.myDsl.ArgMaxOperation;
import org.xtext.example.mydsl.myDsl.ArgMinOperation;
import org.xtext.example.mydsl.myDsl.ConcatOperation;
import org.xtext.example.mydsl.myDsl.DropOperation;
import org.xtext.example.mydsl.myDsl.FilterOperation;
import org.xtext.example.mydsl.myDsl.LimitOperation;
import org.xtext.example.mydsl.myDsl.LoadJSON;
import org.xtext.example.mydsl.myDsl.LoadOperation;
import org.xtext.example.mydsl.myDsl.LoadXML;
import org.xtext.example.mydsl.myDsl.LoadYAML;
import org.xtext.example.mydsl.myDsl.Model;
import org.xtext.example.mydsl.myDsl.MyDslFactory;
import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PrintOperation;
import org.xtext.example.mydsl.myDsl.PrintTable;
import org.xtext.example.mydsl.myDsl.ProcessFoldersOperation;
import org.xtext.example.mydsl.myDsl.RenameOperation;
import org.xtext.example.mydsl.myDsl.SaveOperation;
import org.xtext.example.mydsl.myDsl.SelectOperation;
import org.xtext.example.mydsl.myDsl.TopLevelOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class MyDslPackageImpl extends EPackageImpl implements MyDslPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass modelEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass topLevelOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass loadOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass loadJSONEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass loadXMLEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass loadYAMLEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass selectOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass concatOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass filterOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass saveOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass printOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass printTableEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass renameOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass limitOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass argMaxOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass argMinOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass dropOperationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass processFoldersOperationEClass = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private MyDslPackageImpl()
  {
    super(eNS_URI, MyDslFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link MyDslPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static MyDslPackage init()
  {
    if (isInited) return (MyDslPackage)EPackage.Registry.INSTANCE.getEPackage(MyDslPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredMyDslPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    MyDslPackageImpl theMyDslPackage = registeredMyDslPackage instanceof MyDslPackageImpl ? (MyDslPackageImpl)registeredMyDslPackage : new MyDslPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theMyDslPackage.createPackageContents();

    // Initialize created meta-data
    theMyDslPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theMyDslPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(MyDslPackage.eNS_URI, theMyDslPackage);
    return theMyDslPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getModel()
  {
    return modelEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getModel_Operations()
  {
    return (EReference)modelEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getTopLevelOperation()
  {
    return topLevelOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLoadOperation()
  {
    return loadOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLoadOperation_File()
  {
    return (EAttribute)loadOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLoadOperation_Table()
  {
    return (EAttribute)loadOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLoadOperation_Nested()
  {
    return (EAttribute)loadOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLoadJSON()
  {
    return loadJSONEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLoadJSON_Attributes()
  {
    return (EAttribute)loadJSONEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLoadXML()
  {
    return loadXMLEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLoadYAML()
  {
    return loadYAMLEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSelectOperation()
  {
    return selectOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSelectOperation_Columns()
  {
    return (EAttribute)selectOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSelectOperation_Table()
  {
    return (EAttribute)selectOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSelectOperation_Target()
  {
    return (EAttribute)selectOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getConcatOperation()
  {
    return concatOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConcatOperation_Target()
  {
    return (EAttribute)concatOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getConcatOperation_Tables()
  {
    return (EAttribute)concatOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFilterOperation()
  {
    return filterOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFilterOperation_Column()
  {
    return (EAttribute)filterOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFilterOperation_Table()
  {
    return (EAttribute)filterOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFilterOperation_Condition()
  {
    return (EAttribute)filterOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFilterOperation_Value()
  {
    return (EAttribute)filterOperationEClass.getEStructuralFeatures().get(3);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFilterOperation_Target()
  {
    return (EAttribute)filterOperationEClass.getEStructuralFeatures().get(4);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getSaveOperation()
  {
    return saveOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSaveOperation_Tables()
  {
    return (EAttribute)saveOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSaveOperation_File()
  {
    return (EAttribute)saveOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getSaveOperation_Format()
  {
    return (EAttribute)saveOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPrintOperation()
  {
    return printOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getPrintTable()
  {
    return printTableEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getPrintTable_Table()
  {
    return (EAttribute)printTableEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getRenameOperation()
  {
    return renameOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRenameOperation_Original()
  {
    return (EAttribute)renameOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRenameOperation_Renamed()
  {
    return (EAttribute)renameOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getRenameOperation_Table()
  {
    return (EAttribute)renameOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getLimitOperation()
  {
    return limitOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLimitOperation_Table()
  {
    return (EAttribute)limitOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLimitOperation_Start()
  {
    return (EAttribute)limitOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getLimitOperation_End()
  {
    return (EAttribute)limitOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArgMaxOperation()
  {
    return argMaxOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgMaxOperation_Column()
  {
    return (EAttribute)argMaxOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgMaxOperation_Table()
  {
    return (EAttribute)argMaxOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgMaxOperation_Target()
  {
    return (EAttribute)argMaxOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getArgMinOperation()
  {
    return argMinOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgMinOperation_Column()
  {
    return (EAttribute)argMinOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgMinOperation_Table()
  {
    return (EAttribute)argMinOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getArgMinOperation_Target()
  {
    return (EAttribute)argMinOperationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getDropOperation()
  {
    return dropOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getDropOperation_Table()
  {
    return (EAttribute)dropOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getProcessFoldersOperation()
  {
    return processFoldersOperationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getProcessFoldersOperation_Folders()
  {
    return (EAttribute)processFoldersOperationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getProcessFoldersOperation_FolderOperations()
  {
    return (EReference)processFoldersOperationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MyDslFactory getMyDslFactory()
  {
    return (MyDslFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    modelEClass = createEClass(MODEL);
    createEReference(modelEClass, MODEL__OPERATIONS);

    topLevelOperationEClass = createEClass(TOP_LEVEL_OPERATION);

    loadOperationEClass = createEClass(LOAD_OPERATION);
    createEAttribute(loadOperationEClass, LOAD_OPERATION__FILE);
    createEAttribute(loadOperationEClass, LOAD_OPERATION__TABLE);
    createEAttribute(loadOperationEClass, LOAD_OPERATION__NESTED);

    loadJSONEClass = createEClass(LOAD_JSON);
    createEAttribute(loadJSONEClass, LOAD_JSON__ATTRIBUTES);

    loadXMLEClass = createEClass(LOAD_XML);

    loadYAMLEClass = createEClass(LOAD_YAML);

    selectOperationEClass = createEClass(SELECT_OPERATION);
    createEAttribute(selectOperationEClass, SELECT_OPERATION__COLUMNS);
    createEAttribute(selectOperationEClass, SELECT_OPERATION__TABLE);
    createEAttribute(selectOperationEClass, SELECT_OPERATION__TARGET);

    concatOperationEClass = createEClass(CONCAT_OPERATION);
    createEAttribute(concatOperationEClass, CONCAT_OPERATION__TARGET);
    createEAttribute(concatOperationEClass, CONCAT_OPERATION__TABLES);

    filterOperationEClass = createEClass(FILTER_OPERATION);
    createEAttribute(filterOperationEClass, FILTER_OPERATION__COLUMN);
    createEAttribute(filterOperationEClass, FILTER_OPERATION__TABLE);
    createEAttribute(filterOperationEClass, FILTER_OPERATION__CONDITION);
    createEAttribute(filterOperationEClass, FILTER_OPERATION__VALUE);
    createEAttribute(filterOperationEClass, FILTER_OPERATION__TARGET);

    saveOperationEClass = createEClass(SAVE_OPERATION);
    createEAttribute(saveOperationEClass, SAVE_OPERATION__TABLES);
    createEAttribute(saveOperationEClass, SAVE_OPERATION__FILE);
    createEAttribute(saveOperationEClass, SAVE_OPERATION__FORMAT);

    printOperationEClass = createEClass(PRINT_OPERATION);

    printTableEClass = createEClass(PRINT_TABLE);
    createEAttribute(printTableEClass, PRINT_TABLE__TABLE);

    renameOperationEClass = createEClass(RENAME_OPERATION);
    createEAttribute(renameOperationEClass, RENAME_OPERATION__ORIGINAL);
    createEAttribute(renameOperationEClass, RENAME_OPERATION__RENAMED);
    createEAttribute(renameOperationEClass, RENAME_OPERATION__TABLE);

    limitOperationEClass = createEClass(LIMIT_OPERATION);
    createEAttribute(limitOperationEClass, LIMIT_OPERATION__TABLE);
    createEAttribute(limitOperationEClass, LIMIT_OPERATION__START);
    createEAttribute(limitOperationEClass, LIMIT_OPERATION__END);

    argMaxOperationEClass = createEClass(ARG_MAX_OPERATION);
    createEAttribute(argMaxOperationEClass, ARG_MAX_OPERATION__COLUMN);
    createEAttribute(argMaxOperationEClass, ARG_MAX_OPERATION__TABLE);
    createEAttribute(argMaxOperationEClass, ARG_MAX_OPERATION__TARGET);

    argMinOperationEClass = createEClass(ARG_MIN_OPERATION);
    createEAttribute(argMinOperationEClass, ARG_MIN_OPERATION__COLUMN);
    createEAttribute(argMinOperationEClass, ARG_MIN_OPERATION__TABLE);
    createEAttribute(argMinOperationEClass, ARG_MIN_OPERATION__TARGET);

    dropOperationEClass = createEClass(DROP_OPERATION);
    createEAttribute(dropOperationEClass, DROP_OPERATION__TABLE);

    processFoldersOperationEClass = createEClass(PROCESS_FOLDERS_OPERATION);
    createEAttribute(processFoldersOperationEClass, PROCESS_FOLDERS_OPERATION__FOLDERS);
    createEReference(processFoldersOperationEClass, PROCESS_FOLDERS_OPERATION__FOLDER_OPERATIONS);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    loadOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    loadJSONEClass.getESuperTypes().add(this.getLoadOperation());
    loadXMLEClass.getESuperTypes().add(this.getLoadOperation());
    loadYAMLEClass.getESuperTypes().add(this.getLoadOperation());
    selectOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    concatOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    filterOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    saveOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    printOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    printTableEClass.getESuperTypes().add(this.getPrintOperation());
    renameOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    limitOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    argMaxOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    argMinOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    dropOperationEClass.getESuperTypes().add(this.getTopLevelOperation());
    processFoldersOperationEClass.getESuperTypes().add(this.getTopLevelOperation());

    // Initialize classes and features; add operations and parameters
    initEClass(modelEClass, Model.class, "Model", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getModel_Operations(), this.getTopLevelOperation(), null, "operations", null, 0, -1, Model.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(topLevelOperationEClass, TopLevelOperation.class, "TopLevelOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(loadOperationEClass, LoadOperation.class, "LoadOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLoadOperation_File(), ecorePackage.getEString(), "file", null, 0, 1, LoadOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLoadOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, LoadOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLoadOperation_Nested(), ecorePackage.getEString(), "nested", null, 0, -1, LoadOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(loadJSONEClass, LoadJSON.class, "LoadJSON", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLoadJSON_Attributes(), ecorePackage.getEString(), "attributes", null, 0, -1, LoadJSON.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(loadXMLEClass, LoadXML.class, "LoadXML", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(loadYAMLEClass, LoadYAML.class, "LoadYAML", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(selectOperationEClass, SelectOperation.class, "SelectOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSelectOperation_Columns(), ecorePackage.getEString(), "columns", null, 0, -1, SelectOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSelectOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, SelectOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSelectOperation_Target(), ecorePackage.getEString(), "target", null, 0, 1, SelectOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(concatOperationEClass, ConcatOperation.class, "ConcatOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getConcatOperation_Target(), ecorePackage.getEString(), "target", null, 0, 1, ConcatOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getConcatOperation_Tables(), ecorePackage.getEString(), "tables", null, 0, -1, ConcatOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(filterOperationEClass, FilterOperation.class, "FilterOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFilterOperation_Column(), ecorePackage.getEString(), "column", null, 0, 1, FilterOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFilterOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, FilterOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFilterOperation_Condition(), ecorePackage.getEString(), "condition", null, 0, 1, FilterOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFilterOperation_Value(), ecorePackage.getEString(), "value", null, 0, 1, FilterOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getFilterOperation_Target(), ecorePackage.getEString(), "target", null, 0, 1, FilterOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(saveOperationEClass, SaveOperation.class, "SaveOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getSaveOperation_Tables(), ecorePackage.getEString(), "tables", null, 0, -1, SaveOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSaveOperation_File(), ecorePackage.getEString(), "file", null, 0, 1, SaveOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getSaveOperation_Format(), ecorePackage.getEString(), "format", null, 0, 1, SaveOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(printOperationEClass, PrintOperation.class, "PrintOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(printTableEClass, PrintTable.class, "PrintTable", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getPrintTable_Table(), ecorePackage.getEString(), "table", null, 0, 1, PrintTable.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(renameOperationEClass, RenameOperation.class, "RenameOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getRenameOperation_Original(), ecorePackage.getEString(), "original", null, 0, 1, RenameOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRenameOperation_Renamed(), ecorePackage.getEString(), "renamed", null, 0, 1, RenameOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getRenameOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, RenameOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(limitOperationEClass, LimitOperation.class, "LimitOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getLimitOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, LimitOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLimitOperation_Start(), ecorePackage.getEInt(), "start", null, 0, 1, LimitOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getLimitOperation_End(), ecorePackage.getEInt(), "end", null, 0, 1, LimitOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(argMaxOperationEClass, ArgMaxOperation.class, "ArgMaxOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getArgMaxOperation_Column(), ecorePackage.getEString(), "column", null, 0, 1, ArgMaxOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgMaxOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, ArgMaxOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgMaxOperation_Target(), ecorePackage.getEString(), "target", null, 0, 1, ArgMaxOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(argMinOperationEClass, ArgMinOperation.class, "ArgMinOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getArgMinOperation_Column(), ecorePackage.getEString(), "column", null, 0, 1, ArgMinOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgMinOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, ArgMinOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getArgMinOperation_Target(), ecorePackage.getEString(), "target", null, 0, 1, ArgMinOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(dropOperationEClass, DropOperation.class, "DropOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getDropOperation_Table(), ecorePackage.getEString(), "table", null, 0, 1, DropOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(processFoldersOperationEClass, ProcessFoldersOperation.class, "ProcessFoldersOperation", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getProcessFoldersOperation_Folders(), ecorePackage.getEString(), "folders", null, 0, -1, ProcessFoldersOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getProcessFoldersOperation_FolderOperations(), this.getTopLevelOperation(), null, "folderOperations", null, 0, -1, ProcessFoldersOperation.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Create resource
    createResource(eNS_URI);
  }

} //MyDslPackageImpl
