/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.example.mydsl.myDsl.MyDslPackage;
import org.xtext.example.mydsl.myDsl.PrintOperation;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Print Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class PrintOperationImpl extends TopLevelOperationImpl implements PrintOperation
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected PrintOperationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MyDslPackage.Literals.PRINT_OPERATION;
  }

} //PrintOperationImpl
