/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Load YAML</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getLoadYAML()
 * @model
 * @generated
 */
public interface LoadYAML extends LoadOperation
{
} // LoadYAML
