/**
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.myDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rename Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RenameOperation#getOriginal <em>Original</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RenameOperation#getRenamed <em>Renamed</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.myDsl.RenameOperation#getTable <em>Table</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRenameOperation()
 * @model
 * @generated
 */
public interface RenameOperation extends TopLevelOperation
{
  /**
   * Returns the value of the '<em><b>Original</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Original</em>' attribute.
   * @see #setOriginal(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRenameOperation_Original()
   * @model
   * @generated
   */
  String getOriginal();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RenameOperation#getOriginal <em>Original</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Original</em>' attribute.
   * @see #getOriginal()
   * @generated
   */
  void setOriginal(String value);

  /**
   * Returns the value of the '<em><b>Renamed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Renamed</em>' attribute.
   * @see #setRenamed(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRenameOperation_Renamed()
   * @model
   * @generated
   */
  String getRenamed();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RenameOperation#getRenamed <em>Renamed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Renamed</em>' attribute.
   * @see #getRenamed()
   * @generated
   */
  void setRenamed(String value);

  /**
   * Returns the value of the '<em><b>Table</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Table</em>' attribute.
   * @see #setTable(String)
   * @see org.xtext.example.mydsl.myDsl.MyDslPackage#getRenameOperation_Table()
   * @model
   * @generated
   */
  String getTable();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.myDsl.RenameOperation#getTable <em>Table</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Table</em>' attribute.
   * @see #getTable()
   * @generated
   */
  void setTable(String value);

} // RenameOperation
