- load:
    files:
      - "assignment1Files/decision_tree_1.json"
      - "assignment1Files/decision_tree_2.json"
    as: "some_table"

- rename:
      table: "some_table"
      columns:
        - classes_: "Classes"
        - splitter: "Splitter"
        - ccp_alpha: "CPP Alpha"
        - min_samples_split: "Min Samples Split"

- save:
    table: "some_table"
    columns: ["Criterion", "Splitter", "CPP Alpha", "Min Samples Split"]
    out: "resources/decision_tree_1.csv"