- load:
    - file:
        - path: "assignment1Files/decision_tree_1.json"
        - as: "table1"
    - file:
        - path": "assignment1Files/decision_tree_2.json"
        - as: "table2"

- load:
    - file:
        - path: "assignment1Files/decision_tree_3.yaml"
        - as: "table3"

- rename:
    - target : null
      columns:
        - criterion: "Criterion"
        - splitter: "Splitter"
        - ccp_alpha: "CPP Alpha"
        - min_samples_split: "Min Samples Split"

- save:
    columns: ["Criterion", "Splitter", "CPP Alpha", "Min Samples Split"]
    file: "resources/decision_tree_1.csv"