/*
 * generated by Xtext 2.37.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class MyDslGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.Model");
		private final Assignment cOperationsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cOperationsTopLevelOperationParserRuleCall_0 = (RuleCall)cOperationsAssignment.eContents().get(0);
		
		//Model:
		//    operations+=TopLevelOperation+;
		@Override public ParserRule getRule() { return rule; }
		
		//operations+=TopLevelOperation+
		public Assignment getOperationsAssignment() { return cOperationsAssignment; }
		
		//TopLevelOperation
		public RuleCall getOperationsTopLevelOperationParserRuleCall_0() { return cOperationsTopLevelOperationParserRuleCall_0; }
	}
	public class TopLevelOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.TopLevelOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLoadOperationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSelectOperationParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cConcatOperationParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cSaveOperationParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPrintOperationParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cRenameOperationParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cLimitOperationParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cArgMaxOperationParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		private final RuleCall cArgMinOperationParserRuleCall_8 = (RuleCall)cAlternatives.eContents().get(8);
		private final RuleCall cDropOperationParserRuleCall_9 = (RuleCall)cAlternatives.eContents().get(9);
		private final RuleCall cFilterOperationParserRuleCall_10 = (RuleCall)cAlternatives.eContents().get(10);
		private final RuleCall cProcessFoldersOperationParserRuleCall_11 = (RuleCall)cAlternatives.eContents().get(11);
		
		//TopLevelOperation:
		//    LoadOperation | SelectOperation | ConcatOperation | SaveOperation |
		//    PrintOperation | RenameOperation | LimitOperation |
		//    ArgMaxOperation | ArgMinOperation | DropOperation | FilterOperation | ProcessFoldersOperation;
		@Override public ParserRule getRule() { return rule; }
		
		//LoadOperation | SelectOperation | ConcatOperation | SaveOperation |
		//PrintOperation | RenameOperation | LimitOperation |
		//ArgMaxOperation | ArgMinOperation | DropOperation | FilterOperation | ProcessFoldersOperation
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LoadOperation
		public RuleCall getLoadOperationParserRuleCall_0() { return cLoadOperationParserRuleCall_0; }
		
		//SelectOperation
		public RuleCall getSelectOperationParserRuleCall_1() { return cSelectOperationParserRuleCall_1; }
		
		//ConcatOperation
		public RuleCall getConcatOperationParserRuleCall_2() { return cConcatOperationParserRuleCall_2; }
		
		//SaveOperation
		public RuleCall getSaveOperationParserRuleCall_3() { return cSaveOperationParserRuleCall_3; }
		
		//PrintOperation
		public RuleCall getPrintOperationParserRuleCall_4() { return cPrintOperationParserRuleCall_4; }
		
		//RenameOperation
		public RuleCall getRenameOperationParserRuleCall_5() { return cRenameOperationParserRuleCall_5; }
		
		//LimitOperation
		public RuleCall getLimitOperationParserRuleCall_6() { return cLimitOperationParserRuleCall_6; }
		
		//ArgMaxOperation
		public RuleCall getArgMaxOperationParserRuleCall_7() { return cArgMaxOperationParserRuleCall_7; }
		
		//ArgMinOperation
		public RuleCall getArgMinOperationParserRuleCall_8() { return cArgMinOperationParserRuleCall_8; }
		
		//DropOperation
		public RuleCall getDropOperationParserRuleCall_9() { return cDropOperationParserRuleCall_9; }
		
		//FilterOperation
		public RuleCall getFilterOperationParserRuleCall_10() { return cFilterOperationParserRuleCall_10; }
		
		//ProcessFoldersOperation
		public RuleCall getProcessFoldersOperationParserRuleCall_11() { return cProcessFoldersOperationParserRuleCall_11; }
	}
	public class LoadOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LoadOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLoadJSONParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLoadXMLParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cLoadYAMLParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//LoadOperation:
		//    LoadJSON | LoadXML | LoadYAML;
		@Override public ParserRule getRule() { return rule; }
		
		//LoadJSON | LoadXML | LoadYAML
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//LoadJSON
		public RuleCall getLoadJSONParserRuleCall_0() { return cLoadJSONParserRuleCall_0; }
		
		//LoadXML
		public RuleCall getLoadXMLParserRuleCall_1() { return cLoadXMLParserRuleCall_1; }
		
		//LoadYAML
		public RuleCall getLoadYAMLParserRuleCall_2() { return cLoadYAMLParserRuleCall_2; }
	}
	public class LoadJSONElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LoadJSON");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoadJSONKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFileAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFileSTRINGTerminalRuleCall_2_0 = (RuleCall)cFileAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cIntoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableSTRINGTerminalRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cWithAttributesKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cAttributesAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cAttributesSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cAttributesAssignment_7_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cAttributesAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final RuleCall cAttributesSTRINGTerminalRuleCall_7_2_1_0 = (RuleCall)cAttributesAssignment_7_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cNestedInKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cNestedAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cNestedSTRINGTerminalRuleCall_8_1_0 = (RuleCall)cNestedAssignment_8_1.eContents().get(0);
		private final Group cGroup_8_2 = (Group)cGroup_8.eContents().get(2);
		private final Keyword cCommaKeyword_8_2_0 = (Keyword)cGroup_8_2.eContents().get(0);
		private final Assignment cNestedAssignment_8_2_1 = (Assignment)cGroup_8_2.eContents().get(1);
		private final RuleCall cNestedSTRINGTerminalRuleCall_8_2_1_0 = (RuleCall)cNestedAssignment_8_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_8_3 = (Keyword)cGroup_8.eContents().get(3);
		
		//LoadJSON:
		//    '.loadJSON()'
		//    '.from(' file=STRING ')'
		//    '.into(' table=STRING ')'
		//    ('.withAttributes(' attributes+=STRING (',' attributes+=STRING)* ')')?
		//    ('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'.loadJSON()'
		//'.from(' file=STRING ')'
		//'.into(' table=STRING ')'
		//('.withAttributes(' attributes+=STRING (',' attributes+=STRING)* ')')?
		//('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?
		public Group getGroup() { return cGroup; }
		
		//'.loadJSON()'
		public Keyword getLoadJSONKeyword_0() { return cLoadJSONKeyword_0; }
		
		//'.from('
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//file=STRING
		public Assignment getFileAssignment_2() { return cFileAssignment_2; }
		
		//STRING
		public RuleCall getFileSTRINGTerminalRuleCall_2_0() { return cFileSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.into('
		public Keyword getIntoKeyword_4() { return cIntoKeyword_4; }
		
		//table=STRING
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_5_0() { return cTableSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//('.withAttributes(' attributes+=STRING (',' attributes+=STRING)* ')')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'.withAttributes('
		public Keyword getWithAttributesKeyword_7_0() { return cWithAttributesKeyword_7_0; }
		
		//attributes+=STRING
		public Assignment getAttributesAssignment_7_1() { return cAttributesAssignment_7_1; }
		
		//STRING
		public RuleCall getAttributesSTRINGTerminalRuleCall_7_1_0() { return cAttributesSTRINGTerminalRuleCall_7_1_0; }
		
		//(',' attributes+=STRING)*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//','
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//attributes+=STRING
		public Assignment getAttributesAssignment_7_2_1() { return cAttributesAssignment_7_2_1; }
		
		//STRING
		public RuleCall getAttributesSTRINGTerminalRuleCall_7_2_1_0() { return cAttributesSTRINGTerminalRuleCall_7_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_3() { return cRightParenthesisKeyword_7_3; }
		
		//('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?
		public Group getGroup_8() { return cGroup_8; }
		
		//'.nestedIn('
		public Keyword getNestedInKeyword_8_0() { return cNestedInKeyword_8_0; }
		
		//nested+=STRING
		public Assignment getNestedAssignment_8_1() { return cNestedAssignment_8_1; }
		
		//STRING
		public RuleCall getNestedSTRINGTerminalRuleCall_8_1_0() { return cNestedSTRINGTerminalRuleCall_8_1_0; }
		
		//(',' nested+=STRING)*
		public Group getGroup_8_2() { return cGroup_8_2; }
		
		//','
		public Keyword getCommaKeyword_8_2_0() { return cCommaKeyword_8_2_0; }
		
		//nested+=STRING
		public Assignment getNestedAssignment_8_2_1() { return cNestedAssignment_8_2_1; }
		
		//STRING
		public RuleCall getNestedSTRINGTerminalRuleCall_8_2_1_0() { return cNestedSTRINGTerminalRuleCall_8_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_8_3() { return cRightParenthesisKeyword_8_3; }
	}
	public class LoadXMLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LoadXML");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoadXMLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFileAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFileSTRINGTerminalRuleCall_2_0 = (RuleCall)cFileAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cIntoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableSTRINGTerminalRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cNestedInKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cNestedAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cNestedSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cNestedAssignment_7_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cNestedAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final RuleCall cNestedSTRINGTerminalRuleCall_7_2_1_0 = (RuleCall)cNestedAssignment_7_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//LoadXML:
		//    '.loadXML()'
		//    '.from(' file=STRING ')'
		//    '.into(' table=STRING ')'
		//    ('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'.loadXML()'
		//'.from(' file=STRING ')'
		//'.into(' table=STRING ')'
		//('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?
		public Group getGroup() { return cGroup; }
		
		//'.loadXML()'
		public Keyword getLoadXMLKeyword_0() { return cLoadXMLKeyword_0; }
		
		//'.from('
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//file=STRING
		public Assignment getFileAssignment_2() { return cFileAssignment_2; }
		
		//STRING
		public RuleCall getFileSTRINGTerminalRuleCall_2_0() { return cFileSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.into('
		public Keyword getIntoKeyword_4() { return cIntoKeyword_4; }
		
		//table=STRING
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_5_0() { return cTableSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'.nestedIn('
		public Keyword getNestedInKeyword_7_0() { return cNestedInKeyword_7_0; }
		
		//nested+=STRING
		public Assignment getNestedAssignment_7_1() { return cNestedAssignment_7_1; }
		
		//STRING
		public RuleCall getNestedSTRINGTerminalRuleCall_7_1_0() { return cNestedSTRINGTerminalRuleCall_7_1_0; }
		
		//(',' nested+=STRING)*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//','
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//nested+=STRING
		public Assignment getNestedAssignment_7_2_1() { return cNestedAssignment_7_2_1; }
		
		//STRING
		public RuleCall getNestedSTRINGTerminalRuleCall_7_2_1_0() { return cNestedSTRINGTerminalRuleCall_7_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_3() { return cRightParenthesisKeyword_7_3; }
	}
	public class LoadYAMLElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LoadYAML");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLoadYAMLKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cFileAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cFileSTRINGTerminalRuleCall_2_0 = (RuleCall)cFileAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cIntoKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableSTRINGTerminalRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cNestedInKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cNestedAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cNestedSTRINGTerminalRuleCall_7_1_0 = (RuleCall)cNestedAssignment_7_1.eContents().get(0);
		private final Group cGroup_7_2 = (Group)cGroup_7.eContents().get(2);
		private final Keyword cCommaKeyword_7_2_0 = (Keyword)cGroup_7_2.eContents().get(0);
		private final Assignment cNestedAssignment_7_2_1 = (Assignment)cGroup_7_2.eContents().get(1);
		private final RuleCall cNestedSTRINGTerminalRuleCall_7_2_1_0 = (RuleCall)cNestedAssignment_7_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7_3 = (Keyword)cGroup_7.eContents().get(3);
		
		//LoadYAML:
		//    '.loadYAML()'
		//    '.from(' file=STRING ')'
		//    '.into(' table=STRING ')'
		//    ('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?;
		@Override public ParserRule getRule() { return rule; }
		
		//'.loadYAML()'
		//'.from(' file=STRING ')'
		//'.into(' table=STRING ')'
		//('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?
		public Group getGroup() { return cGroup; }
		
		//'.loadYAML()'
		public Keyword getLoadYAMLKeyword_0() { return cLoadYAMLKeyword_0; }
		
		//'.from('
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//file=STRING
		public Assignment getFileAssignment_2() { return cFileAssignment_2; }
		
		//STRING
		public RuleCall getFileSTRINGTerminalRuleCall_2_0() { return cFileSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.into('
		public Keyword getIntoKeyword_4() { return cIntoKeyword_4; }
		
		//table=STRING
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_5_0() { return cTableSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?
		public Group getGroup_7() { return cGroup_7; }
		
		//'.nestedIn('
		public Keyword getNestedInKeyword_7_0() { return cNestedInKeyword_7_0; }
		
		//nested+=STRING
		public Assignment getNestedAssignment_7_1() { return cNestedAssignment_7_1; }
		
		//STRING
		public RuleCall getNestedSTRINGTerminalRuleCall_7_1_0() { return cNestedSTRINGTerminalRuleCall_7_1_0; }
		
		//(',' nested+=STRING)*
		public Group getGroup_7_2() { return cGroup_7_2; }
		
		//','
		public Keyword getCommaKeyword_7_2_0() { return cCommaKeyword_7_2_0; }
		
		//nested+=STRING
		public Assignment getNestedAssignment_7_2_1() { return cNestedAssignment_7_2_1; }
		
		//STRING
		public RuleCall getNestedSTRINGTerminalRuleCall_7_2_1_0() { return cNestedSTRINGTerminalRuleCall_7_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7_3() { return cRightParenthesisKeyword_7_3; }
	}
	public class ConcatOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ConcatOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cConcatHorizontalKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cToTableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTargetAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTargetSTRINGTerminalRuleCall_2_0 = (RuleCall)cTargetAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOnTablesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTablesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTablesSTRINGTerminalRuleCall_5_0 = (RuleCall)cTablesAssignment_5.eContents().get(0);
		private final Group cGroup_6 = (Group)cGroup.eContents().get(6);
		private final Keyword cCommaKeyword_6_0 = (Keyword)cGroup_6.eContents().get(0);
		private final Assignment cTablesAssignment_6_1 = (Assignment)cGroup_6.eContents().get(1);
		private final RuleCall cTablesSTRINGTerminalRuleCall_6_1_0 = (RuleCall)cTablesAssignment_6_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ConcatOperation:
		//    '.concatHorizontal()'
		//    '.toTable(' target=STRING ')'
		//    '.onTables(' tables+=STRING (',' tables+=STRING)* ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.concatHorizontal()'
		//'.toTable(' target=STRING ')'
		//'.onTables(' tables+=STRING (',' tables+=STRING)* ')'
		public Group getGroup() { return cGroup; }
		
		//'.concatHorizontal()'
		public Keyword getConcatHorizontalKeyword_0() { return cConcatHorizontalKeyword_0; }
		
		//'.toTable('
		public Keyword getToTableKeyword_1() { return cToTableKeyword_1; }
		
		//target=STRING
		public Assignment getTargetAssignment_2() { return cTargetAssignment_2; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_2_0() { return cTargetSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.onTables('
		public Keyword getOnTablesKeyword_4() { return cOnTablesKeyword_4; }
		
		//tables+=STRING
		public Assignment getTablesAssignment_5() { return cTablesAssignment_5; }
		
		//STRING
		public RuleCall getTablesSTRINGTerminalRuleCall_5_0() { return cTablesSTRINGTerminalRuleCall_5_0; }
		
		//(',' tables+=STRING)*
		public Group getGroup_6() { return cGroup_6; }
		
		//','
		public Keyword getCommaKeyword_6_0() { return cCommaKeyword_6_0; }
		
		//tables+=STRING
		public Assignment getTablesAssignment_6_1() { return cTablesAssignment_6_1; }
		
		//STRING
		public RuleCall getTablesSTRINGTerminalRuleCall_6_1_0() { return cTablesSTRINGTerminalRuleCall_6_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
	}
	public class FilterOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.FilterOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFilterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOnColumnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOnTableKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableSTRINGTerminalRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cWhereKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cConditionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cConditionSTRINGTerminalRuleCall_8_0 = (RuleCall)cConditionAssignment_8.eContents().get(0);
		private final Keyword cValueKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Assignment cValueAssignment_10 = (Assignment)cGroup.eContents().get(10);
		private final RuleCall cValueSTRINGTerminalRuleCall_10_0 = (RuleCall)cValueAssignment_10.eContents().get(0);
		private final Group cGroup_11 = (Group)cGroup.eContents().get(11);
		private final Keyword cToTableKeyword_11_0 = (Keyword)cGroup_11.eContents().get(0);
		private final Assignment cTargetAssignment_11_1 = (Assignment)cGroup_11.eContents().get(1);
		private final RuleCall cTargetSTRINGTerminalRuleCall_11_1_0 = (RuleCall)cTargetAssignment_11_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//FilterOperation:
		//    '.filter()'
		//    '.onColumn(' column=STRING ')'
		//    '.onTable(' table=STRING ')'
		//    '.where(' condition=STRING 'value' value=STRING ('toTable' target=STRING)? ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.filter()'
		//'.onColumn(' column=STRING ')'
		//'.onTable(' table=STRING ')'
		//'.where(' condition=STRING 'value' value=STRING ('toTable' target=STRING)? ')'
		public Group getGroup() { return cGroup; }
		
		//'.filter()'
		public Keyword getFilterKeyword_0() { return cFilterKeyword_0; }
		
		//'.onColumn('
		public Keyword getOnColumnKeyword_1() { return cOnColumnKeyword_1; }
		
		//column=STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.onTable('
		public Keyword getOnTableKeyword_4() { return cOnTableKeyword_4; }
		
		//table=STRING
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_5_0() { return cTableSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//'.where('
		public Keyword getWhereKeyword_7() { return cWhereKeyword_7; }
		
		//condition=STRING
		public Assignment getConditionAssignment_8() { return cConditionAssignment_8; }
		
		//STRING
		public RuleCall getConditionSTRINGTerminalRuleCall_8_0() { return cConditionSTRINGTerminalRuleCall_8_0; }
		
		//'value'
		public Keyword getValueKeyword_9() { return cValueKeyword_9; }
		
		//value=STRING
		public Assignment getValueAssignment_10() { return cValueAssignment_10; }
		
		//STRING
		public RuleCall getValueSTRINGTerminalRuleCall_10_0() { return cValueSTRINGTerminalRuleCall_10_0; }
		
		//('toTable' target=STRING)?
		public Group getGroup_11() { return cGroup_11; }
		
		//'toTable'
		public Keyword getToTableKeyword_11_0() { return cToTableKeyword_11_0; }
		
		//target=STRING
		public Assignment getTargetAssignment_11_1() { return cTargetAssignment_11_1; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_11_1_0() { return cTargetSTRINGTerminalRuleCall_11_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_12() { return cRightParenthesisKeyword_12; }
	}
	public class SaveOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SaveOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSaveKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTablesKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTablesAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTablesSTRINGTerminalRuleCall_2_0 = (RuleCall)cTablesAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cTablesAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cTablesSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cTablesAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cToKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFileAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFileSTRINGTerminalRuleCall_6_0 = (RuleCall)cFileAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cAsKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cFormatAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cFormatSTRINGTerminalRuleCall_9_0 = (RuleCall)cFormatAssignment_9.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//SaveOperation:
		//    '.save()'
		//    '.tables(' tables+=STRING (',' tables+=STRING)* ')'
		//    '.to(' file=STRING ')'
		//    '.as(' format=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.save()'
		//'.tables(' tables+=STRING (',' tables+=STRING)* ')'
		//'.to(' file=STRING ')'
		//'.as(' format=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.save()'
		public Keyword getSaveKeyword_0() { return cSaveKeyword_0; }
		
		//'.tables('
		public Keyword getTablesKeyword_1() { return cTablesKeyword_1; }
		
		//tables+=STRING
		public Assignment getTablesAssignment_2() { return cTablesAssignment_2; }
		
		//STRING
		public RuleCall getTablesSTRINGTerminalRuleCall_2_0() { return cTablesSTRINGTerminalRuleCall_2_0; }
		
		//(',' tables+=STRING)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//tables+=STRING
		public Assignment getTablesAssignment_3_1() { return cTablesAssignment_3_1; }
		
		//STRING
		public RuleCall getTablesSTRINGTerminalRuleCall_3_1_0() { return cTablesSTRINGTerminalRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'.to('
		public Keyword getToKeyword_5() { return cToKeyword_5; }
		
		//file=STRING
		public Assignment getFileAssignment_6() { return cFileAssignment_6; }
		
		//STRING
		public RuleCall getFileSTRINGTerminalRuleCall_6_0() { return cFileSTRINGTerminalRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'.as('
		public Keyword getAsKeyword_8() { return cAsKeyword_8; }
		
		//format=STRING
		public Assignment getFormatAssignment_9() { return cFormatAssignment_9; }
		
		//STRING
		public RuleCall getFormatSTRINGTerminalRuleCall_9_0() { return cFormatSTRINGTerminalRuleCall_9_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10() { return cRightParenthesisKeyword_10; }
	}
	public class PrintOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PrintOperation");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cPrintOperationAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final RuleCall cPrintAllParserRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final RuleCall cPrintTableParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//PrintOperation:
		//    {PrintOperation} PrintAll | PrintTable;
		@Override public ParserRule getRule() { return rule; }
		
		//{PrintOperation} PrintAll | PrintTable
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//{PrintOperation} PrintAll
		public Group getGroup_0() { return cGroup_0; }
		
		//{PrintOperation}
		public Action getPrintOperationAction_0_0() { return cPrintOperationAction_0_0; }
		
		//PrintAll
		public RuleCall getPrintAllParserRuleCall_0_1() { return cPrintAllParserRuleCall_0_1; }
		
		//PrintTable
		public RuleCall getPrintTableParserRuleCall_1() { return cPrintTableParserRuleCall_1; }
	}
	public class PrintAllElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PrintAll");
		private final Keyword cPrintAllKeyword = (Keyword)rule.eContents().get(1);
		
		//PrintAll:
		//    '.printAll()';
		@Override public ParserRule getRule() { return rule; }
		
		//'.printAll()'
		public Keyword getPrintAllKeyword() { return cPrintAllKeyword; }
	}
	public class PrintTableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.PrintTable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPrintTableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTableSTRINGTerminalRuleCall_1_0 = (RuleCall)cTableAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//PrintTable:
		//    '.printTable(' table=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.printTable(' table=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.printTable('
		public Keyword getPrintTableKeyword_0() { return cPrintTableKeyword_0; }
		
		//table=STRING
		public Assignment getTableAssignment_1() { return cTableAssignment_1; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_1_0() { return cTableSTRINGTerminalRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class RenameOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.RenameOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cRenameColumnKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cFromKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cOriginalAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cOriginalSTRINGTerminalRuleCall_2_0 = (RuleCall)cOriginalAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cToKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cRenamedAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cRenamedSTRINGTerminalRuleCall_5_0 = (RuleCall)cRenamedAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cOnTableKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTableAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTableSTRINGTerminalRuleCall_8_0 = (RuleCall)cTableAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//RenameOperation:
		//    '.renameColumn()'
		//    '.from(' original=STRING ')'
		//    '.to(' renamed=STRING ')'
		//    '.onTable(' table=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.renameColumn()'
		//'.from(' original=STRING ')'
		//'.to(' renamed=STRING ')'
		//'.onTable(' table=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.renameColumn()'
		public Keyword getRenameColumnKeyword_0() { return cRenameColumnKeyword_0; }
		
		//'.from('
		public Keyword getFromKeyword_1() { return cFromKeyword_1; }
		
		//original=STRING
		public Assignment getOriginalAssignment_2() { return cOriginalAssignment_2; }
		
		//STRING
		public RuleCall getOriginalSTRINGTerminalRuleCall_2_0() { return cOriginalSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.to('
		public Keyword getToKeyword_4() { return cToKeyword_4; }
		
		//renamed=STRING
		public Assignment getRenamedAssignment_5() { return cRenamedAssignment_5; }
		
		//STRING
		public RuleCall getRenamedSTRINGTerminalRuleCall_5_0() { return cRenamedSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//'.onTable('
		public Keyword getOnTableKeyword_7() { return cOnTableKeyword_7; }
		
		//table=STRING
		public Assignment getTableAssignment_8() { return cTableAssignment_8; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_8_0() { return cTableSTRINGTerminalRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class LimitOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.LimitOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLimitKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTableKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTableAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTableSTRINGTerminalRuleCall_2_0 = (RuleCall)cTableAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cFromKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cStartAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cStartINTTerminalRuleCall_5_0 = (RuleCall)cStartAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cToKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cEndAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cEndINTTerminalRuleCall_8_0 = (RuleCall)cEndAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//LimitOperation:
		//    '.limit()'
		//    '.table(' table=STRING ')'
		//    '.from(' start=INT ')'
		//    '.to(' end=INT ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.limit()'
		//'.table(' table=STRING ')'
		//'.from(' start=INT ')'
		//'.to(' end=INT ')'
		public Group getGroup() { return cGroup; }
		
		//'.limit()'
		public Keyword getLimitKeyword_0() { return cLimitKeyword_0; }
		
		//'.table('
		public Keyword getTableKeyword_1() { return cTableKeyword_1; }
		
		//table=STRING
		public Assignment getTableAssignment_2() { return cTableAssignment_2; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_2_0() { return cTableSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.from('
		public Keyword getFromKeyword_4() { return cFromKeyword_4; }
		
		//start=INT
		public Assignment getStartAssignment_5() { return cStartAssignment_5; }
		
		//INT
		public RuleCall getStartINTTerminalRuleCall_5_0() { return cStartINTTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//'.to('
		public Keyword getToKeyword_7() { return cToKeyword_7; }
		
		//end=INT
		public Assignment getEndAssignment_8() { return cEndAssignment_8; }
		
		//INT
		public RuleCall getEndINTTerminalRuleCall_8_0() { return cEndINTTerminalRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class ArgMaxOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ArgMaxOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectMaxKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOnColumnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOnTableKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableSTRINGTerminalRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cToTableKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTargetAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTargetSTRINGTerminalRuleCall_8_0 = (RuleCall)cTargetAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//ArgMaxOperation:
		//    '.selectMax()'
		//    '.onColumn(' column=STRING ')'
		//    '.onTable(' table=STRING ')'
		//    '.toTable(' target=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.selectMax()'
		//'.onColumn(' column=STRING ')'
		//'.onTable(' table=STRING ')'
		//'.toTable(' target=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.selectMax()'
		public Keyword getSelectMaxKeyword_0() { return cSelectMaxKeyword_0; }
		
		//'.onColumn('
		public Keyword getOnColumnKeyword_1() { return cOnColumnKeyword_1; }
		
		//column=STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.onTable('
		public Keyword getOnTableKeyword_4() { return cOnTableKeyword_4; }
		
		//table=STRING
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_5_0() { return cTableSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//'.toTable('
		public Keyword getToTableKeyword_7() { return cToTableKeyword_7; }
		
		//target=STRING
		public Assignment getTargetAssignment_8() { return cTargetAssignment_8; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_8_0() { return cTargetSTRINGTerminalRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class ArgMinOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ArgMinOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectMinKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cOnColumnKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnAssignment_2.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cOnTableKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTableAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cTableSTRINGTerminalRuleCall_5_0 = (RuleCall)cTableAssignment_5.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cToTableKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cTargetAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cTargetSTRINGTerminalRuleCall_8_0 = (RuleCall)cTargetAssignment_8.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//ArgMinOperation:
		//    '.selectMin()'
		//    '.onColumn(' column=STRING ')'
		//    '.onTable(' table=STRING ')'
		//    '.toTable(' target=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.selectMin()'
		//'.onColumn(' column=STRING ')'
		//'.onTable(' table=STRING ')'
		//'.toTable(' target=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.selectMin()'
		public Keyword getSelectMinKeyword_0() { return cSelectMinKeyword_0; }
		
		//'.onColumn('
		public Keyword getOnColumnKeyword_1() { return cOnColumnKeyword_1; }
		
		//column=STRING
		public Assignment getColumnAssignment_2() { return cColumnAssignment_2; }
		
		//STRING
		public RuleCall getColumnSTRINGTerminalRuleCall_2_0() { return cColumnSTRINGTerminalRuleCall_2_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.onTable('
		public Keyword getOnTableKeyword_4() { return cOnTableKeyword_4; }
		
		//table=STRING
		public Assignment getTableAssignment_5() { return cTableAssignment_5; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_5_0() { return cTableSTRINGTerminalRuleCall_5_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_6() { return cRightParenthesisKeyword_6; }
		
		//'.toTable('
		public Keyword getToTableKeyword_7() { return cToTableKeyword_7; }
		
		//target=STRING
		public Assignment getTargetAssignment_8() { return cTargetAssignment_8; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_8_0() { return cTargetSTRINGTerminalRuleCall_8_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_9() { return cRightParenthesisKeyword_9; }
	}
	public class SelectOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.SelectOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSelectKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cColumnsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cColumnsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cColumnsSTRINGTerminalRuleCall_2_0 = (RuleCall)cColumnsAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cCommaKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cColumnsAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cColumnsSTRINGTerminalRuleCall_3_1_0 = (RuleCall)cColumnsAssignment_3_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cFromTableKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cTableAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cTableSTRINGTerminalRuleCall_6_0 = (RuleCall)cTableAssignment_6.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Keyword cToTableKeyword_8 = (Keyword)cGroup.eContents().get(8);
		private final Assignment cTargetAssignment_9 = (Assignment)cGroup.eContents().get(9);
		private final RuleCall cTargetSTRINGTerminalRuleCall_9_0 = (RuleCall)cTargetAssignment_9.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//SelectOperation:
		//    '.select()'
		//    '.columns(' columns+=STRING (',' columns+=STRING)* ')'
		//    '.fromTable(' table=STRING ')'
		//    '.toTable(' target=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.select()'
		//'.columns(' columns+=STRING (',' columns+=STRING)* ')'
		//'.fromTable(' table=STRING ')'
		//'.toTable(' target=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.select()'
		public Keyword getSelectKeyword_0() { return cSelectKeyword_0; }
		
		//'.columns('
		public Keyword getColumnsKeyword_1() { return cColumnsKeyword_1; }
		
		//columns+=STRING
		public Assignment getColumnsAssignment_2() { return cColumnsAssignment_2; }
		
		//STRING
		public RuleCall getColumnsSTRINGTerminalRuleCall_2_0() { return cColumnsSTRINGTerminalRuleCall_2_0; }
		
		//(',' columns+=STRING)*
		public Group getGroup_3() { return cGroup_3; }
		
		//','
		public Keyword getCommaKeyword_3_0() { return cCommaKeyword_3_0; }
		
		//columns+=STRING
		public Assignment getColumnsAssignment_3_1() { return cColumnsAssignment_3_1; }
		
		//STRING
		public RuleCall getColumnsSTRINGTerminalRuleCall_3_1_0() { return cColumnsSTRINGTerminalRuleCall_3_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_4() { return cRightParenthesisKeyword_4; }
		
		//'.fromTable('
		public Keyword getFromTableKeyword_5() { return cFromTableKeyword_5; }
		
		//table=STRING
		public Assignment getTableAssignment_6() { return cTableAssignment_6; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_6_0() { return cTableSTRINGTerminalRuleCall_6_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_7() { return cRightParenthesisKeyword_7; }
		
		//'.toTable('
		public Keyword getToTableKeyword_8() { return cToTableKeyword_8; }
		
		//target=STRING
		public Assignment getTargetAssignment_9() { return cTargetAssignment_9; }
		
		//STRING
		public RuleCall getTargetSTRINGTerminalRuleCall_9_0() { return cTargetSTRINGTerminalRuleCall_9_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_10() { return cRightParenthesisKeyword_10; }
	}
	public class DropOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.DropOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDropTableKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cTableAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cTableSTRINGTerminalRuleCall_1_0 = (RuleCall)cTableAssignment_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//DropOperation:
		//    '.dropTable(' table=STRING ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'.dropTable(' table=STRING ')'
		public Group getGroup() { return cGroup; }
		
		//'.dropTable('
		public Keyword getDropTableKeyword_0() { return cDropTableKeyword_0; }
		
		//table=STRING
		public Assignment getTableAssignment_1() { return cTableAssignment_1; }
		
		//STRING
		public RuleCall getTableSTRINGTerminalRuleCall_1_0() { return cTableSTRINGTerminalRuleCall_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class ProcessFoldersOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.MyDsl.ProcessFoldersOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProcessFoldersKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFoldersAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFoldersSTRINGTerminalRuleCall_1_0 = (RuleCall)cFoldersAssignment_1.eContents().get(0);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword cCommaKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment cFoldersAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall cFoldersSTRINGTerminalRuleCall_2_1_0 = (RuleCall)cFoldersAssignment_2_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cWithKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Keyword cLeftCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cFolderOperationsAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cFolderOperationsTopLevelOperationParserRuleCall_6_0 = (RuleCall)cFolderOperationsAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//ProcessFoldersOperation:
		//    '.processFolders(' folders+=STRING (',' folders+=STRING)* ')'
		//    '.with' '{' folderOperations+=TopLevelOperation+ '}';
		@Override public ParserRule getRule() { return rule; }
		
		//'.processFolders(' folders+=STRING (',' folders+=STRING)* ')'
		//'.with' '{' folderOperations+=TopLevelOperation+ '}'
		public Group getGroup() { return cGroup; }
		
		//'.processFolders('
		public Keyword getProcessFoldersKeyword_0() { return cProcessFoldersKeyword_0; }
		
		//folders+=STRING
		public Assignment getFoldersAssignment_1() { return cFoldersAssignment_1; }
		
		//STRING
		public RuleCall getFoldersSTRINGTerminalRuleCall_1_0() { return cFoldersSTRINGTerminalRuleCall_1_0; }
		
		//(',' folders+=STRING)*
		public Group getGroup_2() { return cGroup_2; }
		
		//','
		public Keyword getCommaKeyword_2_0() { return cCommaKeyword_2_0; }
		
		//folders+=STRING
		public Assignment getFoldersAssignment_2_1() { return cFoldersAssignment_2_1; }
		
		//STRING
		public RuleCall getFoldersSTRINGTerminalRuleCall_2_1_0() { return cFoldersSTRINGTerminalRuleCall_2_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_3() { return cRightParenthesisKeyword_3; }
		
		//'.with'
		public Keyword getWithKeyword_4() { return cWithKeyword_4; }
		
		//'{'
		public Keyword getLeftCurlyBracketKeyword_5() { return cLeftCurlyBracketKeyword_5; }
		
		//folderOperations+=TopLevelOperation+
		public Assignment getFolderOperationsAssignment_6() { return cFolderOperationsAssignment_6; }
		
		//TopLevelOperation
		public RuleCall getFolderOperationsTopLevelOperationParserRuleCall_6_0() { return cFolderOperationsTopLevelOperationParserRuleCall_6_0; }
		
		//'}'
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}
	
	
	private final ModelElements pModel;
	private final TopLevelOperationElements pTopLevelOperation;
	private final LoadOperationElements pLoadOperation;
	private final LoadJSONElements pLoadJSON;
	private final LoadXMLElements pLoadXML;
	private final LoadYAMLElements pLoadYAML;
	private final ConcatOperationElements pConcatOperation;
	private final FilterOperationElements pFilterOperation;
	private final SaveOperationElements pSaveOperation;
	private final PrintOperationElements pPrintOperation;
	private final PrintAllElements pPrintAll;
	private final PrintTableElements pPrintTable;
	private final RenameOperationElements pRenameOperation;
	private final LimitOperationElements pLimitOperation;
	private final ArgMaxOperationElements pArgMaxOperation;
	private final ArgMinOperationElements pArgMinOperation;
	private final SelectOperationElements pSelectOperation;
	private final DropOperationElements pDropOperation;
	private final ProcessFoldersOperationElements pProcessFoldersOperation;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public MyDslGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.pTopLevelOperation = new TopLevelOperationElements();
		this.pLoadOperation = new LoadOperationElements();
		this.pLoadJSON = new LoadJSONElements();
		this.pLoadXML = new LoadXMLElements();
		this.pLoadYAML = new LoadYAMLElements();
		this.pConcatOperation = new ConcatOperationElements();
		this.pFilterOperation = new FilterOperationElements();
		this.pSaveOperation = new SaveOperationElements();
		this.pPrintOperation = new PrintOperationElements();
		this.pPrintAll = new PrintAllElements();
		this.pPrintTable = new PrintTableElements();
		this.pRenameOperation = new RenameOperationElements();
		this.pLimitOperation = new LimitOperationElements();
		this.pArgMaxOperation = new ArgMaxOperationElements();
		this.pArgMinOperation = new ArgMinOperationElements();
		this.pSelectOperation = new SelectOperationElements();
		this.pDropOperation = new DropOperationElements();
		this.pProcessFoldersOperation = new ProcessFoldersOperationElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.MyDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//    operations+=TopLevelOperation+;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//TopLevelOperation:
	//    LoadOperation | SelectOperation | ConcatOperation | SaveOperation |
	//    PrintOperation | RenameOperation | LimitOperation |
	//    ArgMaxOperation | ArgMinOperation | DropOperation | FilterOperation | ProcessFoldersOperation;
	public TopLevelOperationElements getTopLevelOperationAccess() {
		return pTopLevelOperation;
	}
	
	public ParserRule getTopLevelOperationRule() {
		return getTopLevelOperationAccess().getRule();
	}
	
	//LoadOperation:
	//    LoadJSON | LoadXML | LoadYAML;
	public LoadOperationElements getLoadOperationAccess() {
		return pLoadOperation;
	}
	
	public ParserRule getLoadOperationRule() {
		return getLoadOperationAccess().getRule();
	}
	
	//LoadJSON:
	//    '.loadJSON()'
	//    '.from(' file=STRING ')'
	//    '.into(' table=STRING ')'
	//    ('.withAttributes(' attributes+=STRING (',' attributes+=STRING)* ')')?
	//    ('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?;
	public LoadJSONElements getLoadJSONAccess() {
		return pLoadJSON;
	}
	
	public ParserRule getLoadJSONRule() {
		return getLoadJSONAccess().getRule();
	}
	
	//LoadXML:
	//    '.loadXML()'
	//    '.from(' file=STRING ')'
	//    '.into(' table=STRING ')'
	//    ('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?;
	public LoadXMLElements getLoadXMLAccess() {
		return pLoadXML;
	}
	
	public ParserRule getLoadXMLRule() {
		return getLoadXMLAccess().getRule();
	}
	
	//LoadYAML:
	//    '.loadYAML()'
	//    '.from(' file=STRING ')'
	//    '.into(' table=STRING ')'
	//    ('.nestedIn(' nested+=STRING (',' nested+=STRING)* ')')?;
	public LoadYAMLElements getLoadYAMLAccess() {
		return pLoadYAML;
	}
	
	public ParserRule getLoadYAMLRule() {
		return getLoadYAMLAccess().getRule();
	}
	
	//ConcatOperation:
	//    '.concatHorizontal()'
	//    '.toTable(' target=STRING ')'
	//    '.onTables(' tables+=STRING (',' tables+=STRING)* ')';
	public ConcatOperationElements getConcatOperationAccess() {
		return pConcatOperation;
	}
	
	public ParserRule getConcatOperationRule() {
		return getConcatOperationAccess().getRule();
	}
	
	//FilterOperation:
	//    '.filter()'
	//    '.onColumn(' column=STRING ')'
	//    '.onTable(' table=STRING ')'
	//    '.where(' condition=STRING 'value' value=STRING ('toTable' target=STRING)? ')';
	public FilterOperationElements getFilterOperationAccess() {
		return pFilterOperation;
	}
	
	public ParserRule getFilterOperationRule() {
		return getFilterOperationAccess().getRule();
	}
	
	//SaveOperation:
	//    '.save()'
	//    '.tables(' tables+=STRING (',' tables+=STRING)* ')'
	//    '.to(' file=STRING ')'
	//    '.as(' format=STRING ')';
	public SaveOperationElements getSaveOperationAccess() {
		return pSaveOperation;
	}
	
	public ParserRule getSaveOperationRule() {
		return getSaveOperationAccess().getRule();
	}
	
	//PrintOperation:
	//    {PrintOperation} PrintAll | PrintTable;
	public PrintOperationElements getPrintOperationAccess() {
		return pPrintOperation;
	}
	
	public ParserRule getPrintOperationRule() {
		return getPrintOperationAccess().getRule();
	}
	
	//PrintAll:
	//    '.printAll()';
	public PrintAllElements getPrintAllAccess() {
		return pPrintAll;
	}
	
	public ParserRule getPrintAllRule() {
		return getPrintAllAccess().getRule();
	}
	
	//PrintTable:
	//    '.printTable(' table=STRING ')';
	public PrintTableElements getPrintTableAccess() {
		return pPrintTable;
	}
	
	public ParserRule getPrintTableRule() {
		return getPrintTableAccess().getRule();
	}
	
	//RenameOperation:
	//    '.renameColumn()'
	//    '.from(' original=STRING ')'
	//    '.to(' renamed=STRING ')'
	//    '.onTable(' table=STRING ')';
	public RenameOperationElements getRenameOperationAccess() {
		return pRenameOperation;
	}
	
	public ParserRule getRenameOperationRule() {
		return getRenameOperationAccess().getRule();
	}
	
	//LimitOperation:
	//    '.limit()'
	//    '.table(' table=STRING ')'
	//    '.from(' start=INT ')'
	//    '.to(' end=INT ')';
	public LimitOperationElements getLimitOperationAccess() {
		return pLimitOperation;
	}
	
	public ParserRule getLimitOperationRule() {
		return getLimitOperationAccess().getRule();
	}
	
	//ArgMaxOperation:
	//    '.selectMax()'
	//    '.onColumn(' column=STRING ')'
	//    '.onTable(' table=STRING ')'
	//    '.toTable(' target=STRING ')';
	public ArgMaxOperationElements getArgMaxOperationAccess() {
		return pArgMaxOperation;
	}
	
	public ParserRule getArgMaxOperationRule() {
		return getArgMaxOperationAccess().getRule();
	}
	
	//ArgMinOperation:
	//    '.selectMin()'
	//    '.onColumn(' column=STRING ')'
	//    '.onTable(' table=STRING ')'
	//    '.toTable(' target=STRING ')';
	public ArgMinOperationElements getArgMinOperationAccess() {
		return pArgMinOperation;
	}
	
	public ParserRule getArgMinOperationRule() {
		return getArgMinOperationAccess().getRule();
	}
	
	//SelectOperation:
	//    '.select()'
	//    '.columns(' columns+=STRING (',' columns+=STRING)* ')'
	//    '.fromTable(' table=STRING ')'
	//    '.toTable(' target=STRING ')';
	public SelectOperationElements getSelectOperationAccess() {
		return pSelectOperation;
	}
	
	public ParserRule getSelectOperationRule() {
		return getSelectOperationAccess().getRule();
	}
	
	//DropOperation:
	//    '.dropTable(' table=STRING ')';
	public DropOperationElements getDropOperationAccess() {
		return pDropOperation;
	}
	
	public ParserRule getDropOperationRule() {
		return getDropOperationAccess().getRule();
	}
	
	//ProcessFoldersOperation:
	//    '.processFolders(' folders+=STRING (',' folders+=STRING)* ')'
	//    '.with' '{' folderOperations+=TopLevelOperation+ '}';
	public ProcessFoldersOperationElements getProcessFoldersOperationAccess() {
		return pProcessFoldersOperation;
	}
	
	public ParserRule getProcessFoldersOperationRule() {
		return getProcessFoldersOperationAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
